//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStoreClient.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IPurchaseHistoryService")]
    public interface IPurchaseHistoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseHistoryService/viewPurchaseHistory", ReplyAction="http://tempuri.org/IPurchaseHistoryService/viewPurchaseHistoryResponse")]
        System.Data.DataSet viewPurchaseHistory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseHistoryService/viewPurchaseHistory", ReplyAction="http://tempuri.org/IPurchaseHistoryService/viewPurchaseHistoryResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> viewPurchaseHistoryAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseHistoryServiceChannel : MedicalStoreClient.ServiceReference3.IPurchaseHistoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseHistoryServiceClient : System.ServiceModel.ClientBase<MedicalStoreClient.ServiceReference3.IPurchaseHistoryService>, MedicalStoreClient.ServiceReference3.IPurchaseHistoryService {
        
        public PurchaseHistoryServiceClient() {
        }
        
        public PurchaseHistoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseHistoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseHistoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseHistoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet viewPurchaseHistory(int id) {
            return base.Channel.viewPurchaseHistory(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> viewPurchaseHistoryAsync(int id) {
            return base.Channel.viewPurchaseHistoryAsync(id);
        }
    }
}
